// 1x1 픽셀 빨간색 JPEG (base64).
// 실제 이미지 크기는 중요하지 않음 — 우리는 "5장 제한 / 병렬 요청 / 부분 실패" 같은
// 플로우 동작을 검증하지, 실제 압축률을 검증하지 않는다.
// (압축률은 어차피 라이브러리 동작이고, 단위 테스트 영역.)
const ONE_PIXEL_JPEG_BASE64 =
  '/9j/4AAQSkZJRgABAQEASABIAAD/2wBDAAEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQH/wgARCAABAAEDAREAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAACf/EABQBAQAAAAAAAAAAAAAAAAAAAAj/2gAMAwEAAhADEAAAAB//xAAUEAEAAAAAAAAAAAAAAAAAAAAA/9oACAEBAAEFAh//xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oACAEDAQE/AR//xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oACAECAQE/AR//xAAUEAEAAAAAAAAAAAAAAAAAAAAA/9oACAEBAAY/Ah//xAAUEAEAAAAAAAAAAAAAAAAAAAAA/9oACAEBAAE/IR//2gAMAwEAAgADAAAAEB//xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oACAEDAQE/EB//xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oACAECAQE/EB//xAAUEAEAAAAAAAAAAAAAAAAAAAAA/9oACAEBAAE/EB//2Q==';

export function makeTestImage(index: number) {
  return {
    name: `test-${index}.jpg`,
    mimeType: 'image/jpeg',
    buffer: Buffer.from(ONE_PIXEL_JPEG_BASE64, 'base64'),
  };
}

export function makeTestImages(count: number) {
  return Array.from({ length: count }, (_, i) => makeTestImage(i + 1));
}
